//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFT.Services.TransactionProcessor.Test.TransactionProcessorService1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransactionProcessorService1.ITransactionProcessor")]
    public interface ITransactionProcessor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionProcessor/StartMainLoop", ReplyAction="http://tempuri.org/ITransactionProcessor/StartMainLoopResponse")]
        void StartMainLoop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionProcessor/StartMainLoop", ReplyAction="http://tempuri.org/ITransactionProcessor/StartMainLoopResponse")]
        System.Threading.Tasks.Task StartMainLoopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionProcessor/StopMainLoop", ReplyAction="http://tempuri.org/ITransactionProcessor/StopMainLoopResponse")]
        void StopMainLoop();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionProcessor/StopMainLoop", ReplyAction="http://tempuri.org/ITransactionProcessor/StopMainLoopResponse")]
        System.Threading.Tasks.Task StopMainLoopAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionProcessor/GetWorkerThreadState", ReplyAction="http://tempuri.org/ITransactionProcessor/GetWorkerThreadStateResponse")]
        System.Threading.ThreadState GetWorkerThreadState();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransactionProcessor/GetWorkerThreadState", ReplyAction="http://tempuri.org/ITransactionProcessor/GetWorkerThreadStateResponse")]
        System.Threading.Tasks.Task<System.Threading.ThreadState> GetWorkerThreadStateAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionProcessorChannel : GFT.Services.TransactionProcessor.Test.TransactionProcessorService1.ITransactionProcessor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionProcessorClient : System.ServiceModel.ClientBase<GFT.Services.TransactionProcessor.Test.TransactionProcessorService1.ITransactionProcessor>, GFT.Services.TransactionProcessor.Test.TransactionProcessorService1.ITransactionProcessor {
        
        public TransactionProcessorClient() {
        }
        
        public TransactionProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartMainLoop() {
            base.Channel.StartMainLoop();
        }
        
        public System.Threading.Tasks.Task StartMainLoopAsync() {
            return base.Channel.StartMainLoopAsync();
        }
        
        public void StopMainLoop() {
            base.Channel.StopMainLoop();
        }
        
        public System.Threading.Tasks.Task StopMainLoopAsync() {
            return base.Channel.StopMainLoopAsync();
        }
        
        public System.Threading.ThreadState GetWorkerThreadState() {
            return base.Channel.GetWorkerThreadState();
        }
        
        public System.Threading.Tasks.Task<System.Threading.ThreadState> GetWorkerThreadStateAsync() {
            return base.Channel.GetWorkerThreadStateAsync();
        }
    }
}
