/// <reference path="modules/mainmodule.ts" />
/// <reference path="controllers/ordercontroller.ts" />
/// <reference path="services/transactionhandlerservice.ts" />
/// <reference path="services/orderhandlerservice.ts" />
/// <reference path="directives/orderdirective.ts" />
/// <reference path="directives/transactiondirective.ts" />
/// <reference path="controllers/transactioncontroller.ts" />
/// <reference path="controllers/webclientcontroller.ts" />
//# sourceMappingURL=_references.js.map