//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GFT.Website.Api.TransactionProcessorBAK1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TransactionProcessorBAK1.ITransactionProcessor")]
    public interface ITransactionProcessor {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITransactionProcessor/start")]
        void start();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITransactionProcessor/start")]
        System.Threading.Tasks.Task startAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITransactionProcessor/stop")]
        void stop();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITransactionProcessor/stop")]
        System.Threading.Tasks.Task stopAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransactionProcessorChannel : GFT.Website.Api.TransactionProcessorBAK1.ITransactionProcessor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransactionProcessorClient : System.ServiceModel.ClientBase<GFT.Website.Api.TransactionProcessorBAK1.ITransactionProcessor>, GFT.Website.Api.TransactionProcessorBAK1.ITransactionProcessor {
        
        public TransactionProcessorClient() {
        }
        
        public TransactionProcessorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransactionProcessorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionProcessorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransactionProcessorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void start() {
            base.Channel.start();
        }
        
        public System.Threading.Tasks.Task startAsync() {
            return base.Channel.startAsync();
        }
        
        public void stop() {
            base.Channel.stop();
        }
        
        public System.Threading.Tasks.Task stopAsync() {
            return base.Channel.stopAsync();
        }
    }
}
